# Generated by Django 4.1.5 on 2025-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('client_id', models.BigIntegerField()),
                ('sale_id', models.BigIntegerField()),
                ('item_name', models.TextField()),
                ('batch', models.TextField(blank=True, null=True)),
                ('sale_notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('discount', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('tax', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('item_total', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('total_paid', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('payment_method', models.CharField(max_length=255)),
            ],
        ),
    ]
