# Generated by Django 4.2.10 on 2025-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarySalesByDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('total_items', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
                ('avg_revenue', models.DecimalField(decimal_places=5, default=0, max_digits=100)),
            ],
        ),
    ]
