# Generated by Django 4.2.10 on 2025-05-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_summarysalesbydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarysalesbydate',
            old_name='total_items',
            new_name='total_sales',
        ),
    ]
