# Generated by Django 4.2.10 on 2025-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_total_items_summarysalesbydate_total_sales'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sale_date'], name='app_sales_sale_da_afc8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='summarysalesbydate',
            index=models.Index(fields=['sale_date'], name='app_summary_sale_da_ec3168_idx'),
        ),
    ]
