# Generated by Django 4.2.10 on 2025-05-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sales_app_sales_sale_da_afc8ad_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarysalesbydate',
            old_name='total_sales',
            new_name='total_orders',
        ),
        migrations.RemoveField(
            model_name='summarysalesbydate',
            name='avg_revenue',
        ),
    ]
